// <auto-generated />
using System;
using BookIt.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookIt.API.Migrations
{
    [DbContext(typeof(BookItDbContext))]
    [Migration("20241015032153_Seeding data for events")]
    partial class Seedingdataforevents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookIt.API.Models.Domain.Booking", b =>
                {
                    b.Property<Guid>("booking_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("booking_dateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("number_of_tickets")
                        .HasColumnType("int");

                    b.Property<double>("total_price")
                        .HasColumnType("float");

                    b.HasKey("booking_id");

                    b.HasIndex("EventId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BookIt.API.Models.Domain.Event", b =>
                {
                    b.Property<Guid>("event_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("available_tickets")
                        .HasColumnType("int");

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("end_time")
                        .HasColumnType("time");

                    b.Property<string>("event_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<TimeOnly>("start_time")
                        .HasColumnType("time");

                    b.HasKey("event_id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            event_id = new Guid("897a64d7-94b2-428d-9548-1d9c4f78c65c"),
                            artist = "Kunal Kapur",
                            available_tickets = 300,
                            capacity = 300,
                            category = "Food Fest",
                            date = new DateOnly(2024, 11, 16),
                            description = "The Happiest Food Festival 13.0",
                            end_time = new TimeOnly(16, 0, 0),
                            event_name = "Horn OK Please",
                            location = "JLN Stadium, Gate No. 14, Delhi",
                            price = 299.0,
                            start_time = new TimeOnly(12, 0, 0)
                        },
                        new
                        {
                            event_id = new Guid("bcc8c341-ece2-4fec-81ca-3b7f31f3c195"),
                            artist = "Neha Dhupia",
                            available_tickets = 100,
                            capacity = 100,
                            category = "Game",
                            date = new DateOnly(2024, 12, 19),
                            description = "Discover Connections in the Most Exciting Way (18+)",
                            end_time = new TimeOnly(19, 0, 0),
                            event_name = "Thrifty X Genz Strangers Meet",
                            location = "Delhi",
                            price = 599.0,
                            start_time = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            event_id = new Guid("e1772253-33d7-4cd0-a49b-aeeeae35ae29"),
                            artist = "Darshan Raval",
                            available_tickets = 200,
                            capacity = 200,
                            category = "Music",
                            date = new DateOnly(2025, 1, 10),
                            description = "Can't wait to listen to Darshan Raval's new album 'Out Of Control'?",
                            end_time = new TimeOnly(21, 0, 0),
                            event_name = "'Out Of Control' with Blue Family",
                            location = "Saket Social, Delhi",
                            price = 2000.0,
                            start_time = new TimeOnly(18, 0, 0)
                        },
                        new
                        {
                            event_id = new Guid("b60c1f30-a2cc-4453-ae8e-d1ba4677d64e"),
                            artist = "Anubhav Singh Bassi",
                            available_tickets = 70,
                            capacity = 70,
                            category = "Comedy",
                            date = new DateOnly(2025, 2, 2),
                            description = "After the great success of his previous show Bas kar bassi, Anubhav Singh Bassi is coming back to perform live on stage.",
                            end_time = new TimeOnly(12, 0, 0),
                            event_name = "Kisi Ko Batana Mat Ft. Anubhav Singh Bassi",
                            location = "Delhi",
                            price = 799.0,
                            start_time = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            event_id = new Guid("1ccab91a-f452-417b-bb72-787aff994af8"),
                            artist = "Karan Aujla",
                            available_tickets = 200,
                            capacity = 200,
                            category = "Music",
                            date = new DateOnly(2025, 3, 1),
                            description = "Experience the magic of Karaan Aujla live on his It Was All A Dream World Tour!",
                            end_time = new TimeOnly(20, 0, 0),
                            event_name = "It Was All A Dream",
                            location = "Mumbai",
                            price = 1999.0,
                            start_time = new TimeOnly(19, 0, 0)
                        },
                        new
                        {
                            event_id = new Guid("7a08f46b-f298-47b5-a39e-f331f8ddc575"),
                            artist = "Manhar Seth",
                            available_tickets = 60,
                            capacity = 60,
                            category = "Comedy",
                            date = new DateOnly(2025, 1, 2),
                            description = "Manhar Seth's pomedy set 'Main Shayar Toh Nahi' along with some crowdwork",
                            end_time = new TimeOnly(10, 0, 0),
                            event_name = "Main Shayar Toh Nahi ft Manhar Seth",
                            location = "Mehendi Navaz Jung Hall: Ahemdabad",
                            price = 399.0,
                            start_time = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            event_id = new Guid("afb4c67b-f72c-4486-b86f-5690e4b6937f"),
                            artist = "John Flubber",
                            available_tickets = 120,
                            capacity = 120,
                            category = "Acting",
                            date = new DateOnly(2024, 12, 4),
                            description = "Join Flubber, the renowned award-winning clown and creator of India's International Clown Festival, on another exhilarating adventure.",
                            end_time = new TimeOnly(15, 0, 0),
                            event_name = "International Clown Festival - Chennai",
                            location = "Sri Mutha Venkatasubba Rao Concert Hall: Chennai",
                            price = 800.0,
                            start_time = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            event_id = new Guid("a5807ecd-be61-4845-8645-c88ac1e79e4b"),
                            artist = "All kids who join us",
                            available_tickets = 50,
                            capacity = 50,
                            category = "Competition",
                            date = new DateOnly(2024, 11, 2),
                            description = "CoComelon - Family & Friends are coming to India for the first time…for a Play Date!",
                            end_time = new TimeOnly(10, 0, 0),
                            event_name = "Cocomelon Comes To Ahmedabad!",
                            location = "Palladium Mall: Ahemdabad",
                            price = 100.0,
                            start_time = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            event_id = new Guid("b8c62ec5-70b6-4618-a289-d357245c5dc0"),
                            artist = "Gaurav Gupta",
                            available_tickets = 60,
                            capacity = 60,
                            category = "Comedy",
                            date = new DateOnly(2024, 12, 10),
                            description = "Diwali Celebration",
                            end_time = new TimeOnly(11, 0, 0),
                            event_name = "Gaurav Gupta Live",
                            location = "Talkatora Stadium Delhi",
                            price = 799.0,
                            start_time = new TimeOnly(10, 0, 0)
                        });
                });

            modelBuilder.Entity("BookIt.API.Models.Domain.Booking", b =>
                {
                    b.HasOne("BookIt.API.Models.Domain.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });
#pragma warning restore 612, 618
        }
    }
}
