// <auto-generated />
using System;
using BookIt.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookIt.API.Migrations
{
    [DbContext(typeof(BookItDbContext))]
    partial class BookItDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookIt.API.Models.Domain.Booking", b =>
                {
                    b.Property<Guid>("booking_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("booking_dateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("number_of_tickets")
                        .HasColumnType("int");

                    b.Property<double>("total_price")
                        .HasColumnType("float");

                    b.HasKey("booking_id");

                    b.HasIndex("EventId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BookIt.API.Models.Domain.Event", b =>
                {
                    b.Property<Guid>("event_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("end_time")
                        .HasColumnType("time");

                    b.Property<string>("event_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<TimeOnly>("start_time")
                        .HasColumnType("time");

                    b.HasKey("event_id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            event_id = new Guid("f09ce828-2207-4927-be79-459bf96ee99f"),
                            artist = "Gaurav Kapoor",
                            category = "Comedy Shows",
                            date = new DateOnly(2024, 10, 10),
                            description = "Laughter therapy",
                            end_time = new TimeOnly(10, 0, 0),
                            event_name = "Comedy Nights",
                            location = "Noida",
                            price = 2000.0,
                            start_time = new TimeOnly(9, 0, 0)
                        });
                });

            modelBuilder.Entity("BookIt.API.Models.Domain.Booking", b =>
                {
                    b.HasOne("BookIt.API.Models.Domain.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });
#pragma warning restore 612, 618
        }
    }
}
